repos:
    # -   repo: https://github.com/pre-commit/pre-commit-hooks
    - repo: git@github.com:pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: check-added-large-files
          - id: check-ast
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-yaml
          - id: end-of-file-fixer
    # -   repo: https://github.com/asottile/reorder_python_imports
    - repo: git@github.com:asottile/reorder_python_imports
      rev: v3.9.0
      hooks:
          - id: reorder-python-imports
            exclude: ^docs/
    - repo: local
      hooks:
          - id: black
            name: black
            entry: black
            language: system
            types: [python]
            exclude: ^docs/
            verbose: true
          - id: yapf
            name: yapf
            entry: yapf -r -i
            language: system
            types: [python]
            exclude: ^docs/
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
            exclude: ^docs/
          - id: mdformat
            name: mdformat
            entry: mdformat
            language: system
            types: [markdown]
            exclude: |
                (?x)^(
                    CHANGELOG.md|
                    README.md
                )$
